FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y curl && apt-get install -y apt-transport-https && apt-get install -y vim && apt-get install -y ssh
RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
RUN echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
RUN apt-get update
RUN apt-get install -y kubectl
